In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

/Users/coffee/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [3]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())

这将在当前目录中生成一个 event 文件，其名称格式如下：

events.out.tfevents.{timestamp}.{hostname}

现在，在新的终端中使用以下 shell 命令启动 TensorBoard：

tensorboard --logdir .

In [4]:
sess = tf.Session()
print(sess.run(total))

7.0


In [5]:
print(sess.run({'ab':(a, b), 'total':total}))

{'ab': (3.0, 4.0), 'total': 7.0}


In [6]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.45303595 0.79641247 0.42225122]
[0.08258247 0.54708457 0.55951273]
(array([1.8139992, 1.1451991, 1.064908 ], dtype=float32), array([2.8139992, 2.145199 , 2.064908 ], dtype=float32))


*供给*

In [7]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [8]:
print(sess.run(z, feed_dict={x:1, y:2}))
print(sess.run(z, feed_dict={x:[1,2], y:[3,4]}))

3.0
[4. 6.]


*数据集*

In [9]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [10]:
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1]
[2 3]
[4 5]
[6 7]


*创建层*

In [11]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

*初始化层*

In [12]:
init = tf.global_variables_initializer()
sess.run(init)

In [13]:
print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]}))

[[-2.7397285]
 [-5.03284  ]]


*特征列*

In [14]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [15]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [16]:
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


#### 训练一个小回归

In [17]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

In [18]:
linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)

In [19]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))

[[-1.1264331]
 [-2.2528663]
 [-3.3792994]
 [-4.5057325]]


In [20]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

print(sess.run(loss))

1.7520558


In [21]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [22]:
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

1.7520558
1.2525964
0.90581185
0.6649661
0.49763045
0.38130307
0.30037084
0.24399959
0.20467211
0.17717217
0.1578803
0.14428516
0.13464409
0.12774795
0.122757636
0.11909101
0.116344064
0.11423645
0.112573676
0.11122081
0.1100841
0.109098606
0.10821919
0.10741461
0.10666302
0.10594946
0.10526333
0.10459742
0.1039467
0.103307664
0.10267779
0.102055416
0.101439394
0.100828804
0.10022312
0.099621944
0.099024974
0.09843199
0.097842805
0.09725738
0.09667555
0.09609734
0.09552265
0.09495143
0.09438366
0.093819305
0.09325832
0.09270071
0.092146456
0.091595516
0.09104785
0.09050352
0.08996238
0.08942452
0.08888987
0.08835841
0.08783013
0.087304994
0.08678301
0.086264156
0.08574842
0.08523572
0.0847261
0.08421956
0.08371601
0.083215475
0.08271795
0.08222339
0.08173178
0.08124313
0.08075739
0.080274545
0.0797946
0.07931752
0.07884328
0.078371905
0.077903345
0.077437565
0.076974586
0.07651436
0.07605687
0.07560217
0.07515013
0.074700825
0.0742542
0.07381024
0.073368944
0.07293028
0.07249423
0.0720

In [23]:
print(sess.run(y_pred))

[[-0.41938698]
 [-1.2032217 ]
 [-1.9870564 ]
 [-2.7708912 ]]
